### ISSUE TITLE
Failed to update pipeline

### ISSUE THREAD

**Issue by runlevel5** [pulumiverse/pulumi-buildkite#109]
**Version:** 2.2.0
**Description:** Failed to update existing pipeline
**Steps to reproduce:**

* Provision a new pipeline
* Make any change to pipeline attributes
* Then `pulumi up`

**Expected:** no errors
**Actual:** 

```
buildkite:Pipeline:Pipeline (pipelineName):
    error: 1 error occurred:
    	* updating urn:pulumi:stackName::buildkite-pipelines::buildkite:Pipeline/pipeline:Pipeline::pipelineName: 1 error occurred:
    	* input:2: Variable $input of type PipelineUpdateInput! was provided invalid value for buildRetentionEnabled (Field is not defined on PipelineUpdateInput)
```

**Notes:**

I have a look into the structure of `Pipeline` class but could not find the `buildRetentionEnabled`, however such attribute does exist in the terraform counterpart. 

And the [PR 291](https://github.com/buildkite/terraform-provider-buildkite/pull/291) might be the solution?

**Comment by runlevel5** [comment]
@muhlba91 FYI the Terraform provider has just released `v.1.4.1` 3 days ago. Perhaps we could get #97 updated with the new version? Please let me know if you want any help from me.

**Comment by muhlba91** [comment]
yes, i updated that PR already shortly after i replied to you. it's based on `v1.4.1` by now. 😃

**Comment by runlevel5** [comment]
I urge users who are impacted with this issue to bump to v3
