### ISSUE TITLE
.NET package is not published.

### ISSUE THREAD

**Issue by ringods** [pulumiverse/pulumi-buildkite#26]
The .NET package is not published, although the Github Actions run didn't error. Reason is this:

https://github.com/pulumiverse/pulumi-buildkite/blob/99cff5740d9ba63985f0befb98fb1406207267cf/.github/workflows/release.yml#L148

The `find ... -name 'Pulumi.*.nupkg'` doesn render any results becuause the prefix for us is `Pulumiverse`. Preferrably drop the `find` command. See the command used by another provider:

https://github.com/pulumiverse/pulumi-astra/blob/b7f7bb45d90cde3cc3d7c9061e57fc336433eccb/.github/workflows/release.yml#L121

Can you update the workflow and create a new release?

**Comment by muhlba91** [comment]
now available at: https://www.nuget.org/packages/Pulumiverse.Buildkite
