### ISSUE TITLE
"No ID was supplied" error

### ISSUE THREAD

**Issue by runlevel5** [pulumiverse/pulumi-buildkite#53]
### System info

```
nodejs 18.16.1
pulumi 3.74.0
pulumi-buildkite 2.2.0 # I can confirm 2.3.0 also suffer the same issue
macos 13.4.1 (22F82) arm64
```

### Steps to re-produce

* Make a new `index.ts` to create just one example pipeline
* Then run `pulumi up` then `y`
* Expected:  No error
* Actual:

```
View in Browser (Ctrl+O): https://app.pulumi.com/compono/buildkite-pipelines/trung/updates/2

     Type                            Name                       Status                  Info
     pulumi:pulumi:Stack             buildkite-pipelines-trung  **failed**              1 error; 1 warning
 +   └─ buildkite:Pipeline:Pipeline  trung-pipeline             **creating failed**     1 error


Diagnostics:
  pulumi:pulumi:Stack (buildkite-pipelines-trung):

  buildkite:Pipeline:Pipeline (trung-pipeline):
    error: 1 error occurred:
    	* No ID was supplied
```

I did not have this issue last week; it's happened today when I tried to make changes to existing pipelines so I re-create the codes just to do one HelloWorld pipeline to verify the issue. 

I am trying to search for keyword `No ID was supplied` but could not find any in the provider code.

Unsure if it is a bug or not.

### Codes

```js
    const stepsFile = "hello_world.yml";
    const repositoryName = "hello_world"; // This is a private GitHub repo
    const organizationName = "runlevel5";
  
    const pipelineConfig = {
      name: pipelineName,
      repository: `git@github.com:${organizationName}/${repositoryName}.git`,
      steps: fs.readFileSync(`./pipelines/${stepsFile}`, "utf8"),
      branchConfiguration: "*",
      defaultBranch: "main",
      description: 'trung',
      allowRebuilds: true,
      providerSettings: {
        buildBranches: true,
        buildTags: false,
        buildPullRequests: true,
        publishCommitStatus: true,
        publishBlockedAsPending: true,
        skipPullRequestBuildsForExistingCommits: false,
        triggerMode: "code",
      },
      teams:
        [
          {
            slug: "everyone",
            accessLevel: "BUILD_AND_READ",
          },
          {
            slug: "admin",
            accessLevel: "MANAGE_BUILD_AND_READ"
          }
        ]
    };

    const pipelineInstance = new buildkite.pipeline.Pipeline("trung-pipeline", pipelineConfig);

```

**Comment by muhlba91** [comment]
hi, did you also test this with testing the upstream terraform provider (https://github.com/buildkite/terraform-provider-buildkite/tree/main/buildkite) to verify this isn‘t an „upstream“ issue?

btw. 2.3.0 uses upstream 0.20.0, and 2.2.0 uses upstream 0.19.0.

**Comment by runlevel5** [comment]
I tested 2.2.0 and 2.3.0. Both yield the same error.

I am going to try out the terraform provider in terraform HCL to see if I could re-create the issue.

**Comment by runlevel5** [comment]
I've just tested upstream terraform-provider-buildkite v0.20.0. It works fine. So it is not upstream bug.

**Comment by runlevel5** [comment]
I've just pushed my helloworld demo app to https://github.com/runlevel5/pulumi-buildkite-hello-world

**Comment by runlevel5** [comment]
I've finally found out the issue. It turns out the `admin` team has been renamed manually so the code could not pick up the ID hence the error. My apology for lodging this ticket without checking that first.

**Comment by muhlba91** [comment]
no problems! i‘m happy to hear it got solved and was not an issue in the provider. :)
