### ISSUE TITLE
Example on how to read YAML file into steps property is not correct

### ISSUE THREAD

**Issue by runlevel5** [pulumiverse/pulumi-buildkite#8]
In the [example](https://github.com/grapl-security/pulumi-buildkite/blob/649005fd7a905e04006c8b72a359b05227f329c0/sdk/nodejs/pipeline.ts#L45), the `steps` takes in the `Buffer` of `fs.readFileSync` which is not correct because `steps` takes `pulumi.Input<string>` type instead.

Unless there is a helper that do so that I am not aware of.

**Comment by christophermaier** [comment]
@runlevel5 This example was automatically generated by Pulumi's code-generation tooling, based on the examples present in the Buildkite Terraform provider. I've noticed some other inconsistencies with documentation generation apart from this, and will be following up with some folks from Pulumi to determine the best way to address them. I'll make sure to raise this example with them as well.

Thanks for bringing this to our attention! 🙏

**Comment by runlevel5** [comment]
@christophermaier thanks for the reply and keep up the great work.
